/**
 * Codex Dashboard Generator
 * Lightweight JSON & HTML exporter for Codex CI Dashboard
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

// Resolve __dirname in ES modules
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Output directory (from CI or default)
const OUTPUT_DIR =
  process.env.CODEX_OUTPUT_DIR ||
  path.join(process.cwd(), "codex-output");

// Ensure clean folder
if (fs.existsSync(OUTPUT_DIR)) {
  fs.rmSync(OUTPUT_DIR, { recursive: true, force: true });
}
fs.mkdirSync(OUTPUT_DIR, { recursive: true });

//
// ------------------------------------------------------------
// 1. Generate JSON Data
// ------------------------------------------------------------
// These can later be replaced with real metrics.
// For now, deterministic + valid JSON.
// ------------------------------------------------------------
//

const summary = {
  generatedAt: new Date().toISOString(),
  version: "1.0.0",
  message: "Codex Dashboard generated successfully.",
};

const stats = {
  totalTests: 42,
  testsPassed: 40,
  testsFailed: 2,
  uptimeHours: 123,
  buildCount: 17,
};

const history = [
  { run: 1, passed: 38, failed: 4 },
  { run: 2, passed: 39, failed: 3 },
  { run: 3, passed: 40, failed: 2 }
];

fs.writeFileSync(
  path.join(OUTPUT_DIR, "summary.json"),
  JSON.stringify(summary, null, 2)
);

fs.writeFileSync(
  path.join(OUTPUT_DIR, "stats.json"),
  JSON.stringify(stats, null, 2)
);

fs.writeFileSync(
  path.join(OUTPUT_DIR, "history.json"),
  JSON.stringify(history, null, 2)
);

//
// ------------------------------------------------------------
// 2. Generate HTML Dashboard
// ------------------------------------------------------------
//

const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>Codex Dashboard</title>
  <style>
    body { font-family: Arial, sans-serif; padding: 2rem; }
    h1 { color: #0055aa; }
    pre { background: #f4f4f4; padding: 1rem; border-radius: 6px; }
  </style>
</head>
<body>
  <h1>Codex Dashboard</h1>
  <p>This dashboard is auto-generated by CI.</p>

  <h2>Files</h2>
  <ul>
    <li><a href="./summary.json">summary.json</a></li>
    <li><a href="./stats.json">stats.json</a></li>
    <li><a href="./history.json">history.json</a></li>
  </ul>

  <p><em>Generated at: ${summary.generatedAt}</em></p>
</body>
</html>
`;

fs.writeFileSync(
  path.join(OUTPUT_DIR, "index.html"),
  html.trim()
);

console.log(`📊 Codex Dashboard generated at: ${OUTPUT_DIR}`);
